exclude: ".json"
repos:
#  - repo: https://github.com/psf/black
#    rev: 19.10b0
#    hooks:
#      - id: black

#  - repo: https://github.com/pre-commit/mirrors-mypy
#    rev: v0.782
#    hooks:
#    - id: mypy

#  - repo: https://gitlab.com/pycqa/flake8
#    rev: 3.7.8
#    hooks:
#      - id: flake8

  - repo: https://github.com/timothycrosley/isort
    rev: 4.3.21-2
    hooks:
      - id: isort
        additional_dependencies: [pyproject]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: trailing-whitespace
        exclude: ^tests/.*/fixtures/.*
      - id: end-of-file-fixer
        exclude: ^tests/.*/fixtures/.*
      - id: debug-statements
